// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNIMj3VIFkQcCjLepzxPrD6wFEIOs0eIw',
    appId: '1:371154953544:web:b28d4d166d9ecf946e3f7d',
    messagingSenderId: '371154953544',
    projectId: 'lentaladapter',
    authDomain: 'lentaladapter.firebaseapp.com',
    databaseURL: 'https://lentaladapter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lentaladapter.appspot.com',
    measurementId: 'G-8Y1EXX56M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr4xUNmr1-RY91hcaOt_nPttwlEmsxGhc',
    appId: '1:371154953544:android:d9cea6525fee1e046e3f7d',
    messagingSenderId: '371154953544',
    projectId: 'lentaladapter',
    databaseURL: 'https://lentaladapter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lentaladapter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcyRgQcDBAXuW9CxP4Eor6DK1Asu1F94c',
    appId: '1:371154953544:ios:c8cc13dc06e016896e3f7d',
    messagingSenderId: '371154953544',
    projectId: 'lentaladapter',
    databaseURL: 'https://lentaladapter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lentaladapter.appspot.com',
    androidClientId: '371154953544-ho1srv034hpte0lagug0o46nb04sh0ui.apps.googleusercontent.com',
    iosClientId: '371154953544-nbo6950jnfnspinn9j53l0rlpll1c459.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcyRgQcDBAXuW9CxP4Eor6DK1Asu1F94c',
    appId: '1:371154953544:ios:b4f2371c0beaf67d6e3f7d',
    messagingSenderId: '371154953544',
    projectId: 'lentaladapter',
    databaseURL: 'https://lentaladapter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lentaladapter.appspot.com',
    androidClientId: '371154953544-ho1srv034hpte0lagug0o46nb04sh0ui.apps.googleusercontent.com',
    iosClientId: '371154953544-5pso1phb65sva4p0700du3sh0i7k045b.apps.googleusercontent.com',
    iosBundleId: 'com.example.application.RunnerTests',
  );
}
